### PR TITLE
Default reset() implementation on TNode

### PR DESCRIPTION
**Pull request by berosoboy**

### CODE REVIEW

**Comment by berosoboy** [comment]
Understood.
As alternative, I suggest to create a CompositeTNode class and move the children property to it. And we can implement the reset() there.
This solve the problem for leaf nodes too, like Task and WaitNode, which should not have children. Task and WaitNode could extends TNode directly

**Comment by berosoboy** [comment]
> I don't like it man. Loop array always creating iterator down in gdscript implementations which is way worst performance. It is better the old ways. If we are sure the node only have 1 child then just accessing normally is faster. Until they implement better gdscript it is bad.

I made some tests. I created an array with one element and compared both ways. In my results, the test_loop() function always performed better.

```gdscript
var children = ['test']

func test_front():
	if not children.empty():
		var c = children.front()
		pass

func test_loop():
	for c in children:
		pass

func _ready():
	var tests_qty = 1000000
	var start1 = OS.get_ticks_msec()
	for i in range(tests_qty):
		test_front()
	var end1 = OS.get_ticks_msec()
	var test_front_time = end1 - start1
	
	var start2 = OS.get_ticks_msec()
	for i in range(tests_qty):
		test_loop()
	var end2 = OS.get_ticks_msec()
	var test_loop_time = end2 - start2
	
	print("With front access: ", test_front_time, "ms")
	print("With loop: ", test_loop_time, "ms")
```
Could you try the code on your machine too, to see the results?

**Comment by fian46** [comment]
I'll test your code in my machine.

**Comment by fian46** [comment]
I like the idea having CompositeTNode and TNode. I have some idea but never done by my self to. It something like have 3 base classes MultiChildTNode, SingleChildTNode and TNode. It sounds like your idea. Basically Multi child node have array of children. Single child have only property children and TNode have no children. What do you think ?

**Comment by fian46** [comment]
Whoa you're right 😂. It is faster. Probably that if empty make it slower.

**Comment by fian46** [comment]
Hey can you refactoring it to your idea with CompositeTNode instead ? It sounds brilliant.

**Comment by berosoboy** [comment]
> Hey can you refactoring it to your idea with CompositeTNode instead ? It sounds brilliant.

Alright! Let's do it! I agree with your idea of using tree base classes.
According to this [article](https://www.gamasutra.com/blogs/ChrisSimpson/20140717/221339/Behavior_trees_for_AI_How_they_work.php) there are three main archetypes of behaviour tree node: Composite, Decorator and Leaf nodes.
Could we use CompositeTNode and DecoratorTNode class names?

**Comment by fian46** [comment]
I agree with that. Thanks man

**Pull request merged**
